[package]
name = "werewolf"
version = "0.1.0"
edition = "2021"

[dependencies]
imitatort_stateless_company = { path = "../.." }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
